<?php
/**
 *
 * This file should always cause warnings to be generated by phpcs
 *
 */

function register_scripts() {
    wp_register_style( 'style-css', '/css/style.css', array(), '0.0.0', 'all' );

    wp_enqueue_style( 'style1', '/css/style1.css', '', '0.0.1' );
    wp_enqueue_style( 'style2', '/css/style2.css', '', '0.0.2' );

    wp_enqueue_style( 'style-with-todo', 'style-with-todo.css', '', '0.0.1' );  // TODO: Load this conditionally

    wp_enqueue_script( 'jquery', '/js/vendor/jquery.min.js', '', '3.2.1' );
}
add_action( 'wp_enqueue_scripts', 'register_scripts' );
